-- =================================================================
-- SCRIPT PARA ROBUSTECER EL MÓDULO DE CLIENTES (v2)
-- Añade manejo de crédito, saldo y campos adicionales.
-- =================================================================

-- 1. MODIFICAR LA TABLA 'clientes' PARA AÑADIR LOS NUEVOS CAMPOS
ALTER TABLE public.clientes
    ADD COLUMN IF NOT EXISTS numero_identificacion TEXT,
    ADD COLUMN IF NOT EXISTS observaciones TEXT,
    ADD COLUMN IF NOT EXISTS avatar_url TEXT,
    ADD COLUMN IF NOT EXISTS telefono_secundario TEXT,
    ADD COLUMN IF NOT EXISTS permite_credito BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS saldo_actual NUMERIC(10, 2) DEFAULT 0.00;


-- 2. CREAR LA NUEVA TABLA 'movimientos_credito_cliente'
-- Aquí se registrará cada cargo o abono al saldo del cliente, creando un historial perfecto.
CREATE TABLE IF NOT EXISTS public.movimientos_credito_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id UUID NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
    tipo_movimiento TEXT NOT NULL, -- 'cargo' (aumenta deuda) o 'abono' (reduce deuda)
    monto NUMERIC(10, 2) NOT NULL,
    motivo TEXT, -- Ej: "Venta a crédito Pedido #1024", "Abono en efectivo"
    pedido_id BIGINT REFERENCES public.pedidos(id),
    insert_date TIMESTAMPTZ DEFAULT now(),
    insert_by_user UUID DEFAULT auth.uid()
);

ALTER TABLE public.movimientos_credito_cliente ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir gestión de crédito a admins" ON public.movimientos_credito_cliente
FOR ALL USING (check_permission('clientes.credito.gestionar'));


-- 3. FUNCIÓN Y TRIGGER PARA AUTOMATIZAR EL SALDO DEL CLIENTE
-- Esta función se ejecutará automáticamente para actualizar el 'saldo_actual' del cliente
-- cada vez que se inserte un nuevo movimiento de crédito.
CREATE OR REPLACE FUNCTION public.actualizar_saldo_cliente()
RETURNS TRIGGER AS $$
BEGIN
    IF (NEW.tipo_movimiento = 'cargo') THEN
        UPDATE public.clientes
        SET saldo_actual = saldo_actual + NEW.monto
        WHERE id = NEW.cliente_id;
    ELSIF (NEW.tipo_movimiento = 'abono') THEN
        UPDATE public.clientes
        SET saldo_actual = saldo_actual - NEW.monto
        WHERE id = NEW.cliente_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Eliminamos el trigger si ya existe para evitar duplicados, y lo creamos.
DROP TRIGGER IF EXISTS on_movimiento_credito_insert ON public.movimientos_credito_cliente;
CREATE TRIGGER on_movimiento_credito_insert
AFTER INSERT ON public.movimientos_credito_cliente
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_saldo_cliente();


-- 4. AÑADIR NUEVOS PERMISOS PARA LA GESTIÓN DE CRÉDITO
INSERT INTO public.permisos (nombre, descripcion)
VALUES
    ('clientes.credito.gestionar', 'Permite añadir o sustraer saldo de un cliente'),
    ('clientes.credito.permitir', 'Permite activar o desactivar las ventas a crédito para un cliente')
ON CONFLICT (nombre) DO NOTHING;

-- Asignar los nuevos permisos al rol de 'admin'
INSERT INTO public.rol_permisos (rol_id, permiso_id)
SELECT
    (SELECT id FROM public.roles WHERE nombre = 'admin'),
    p.id
FROM public.permisos p
WHERE p.nombre LIKE 'clientes.credito.%'
ON CONFLICT DO NOTHING;