/*
  # Sistema de gestión de proveedores y costos por insumo

  1. Nuevas Tablas
    - `proveedores`
      - `id` (bigint, primary key)
      - `nombre` (text, not null)
      - `contacto_nombre` (text)
      - `telefono` (text)
      - `email` (text)
      - `direccion` (text)
      - `notas` (text)
      - `created_at` (timestamptz)
    - `proveedor_insumos`
      - `proveedor_id` (bigint, foreign key)
      - `insumo_id` (bigint, foreign key)
      - `costo_especifico` (numeric)
      - `es_proveedor_activo` (boolean)
      - `updated_at` (timestamptz)
  
  2. Seguridad
    - Enable RLS en ambas tablas
    - Políticas para usuarios autenticados
  
  3. Automatización
    - Función y trigger para garantizar un único proveedor activo por insumo
*/

-- 1. TABLA PARA GESTIONAR PROVEEDORES
CREATE TABLE IF NOT EXISTS public.proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    contacto_nombre TEXT,
    telefono TEXT,
    email TEXT,
    direccion TEXT,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.proveedores IS 'Catálogo de proveedores de insumos.';

ALTER TABLE public.proveedores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir gestión de proveedores a usuarios autenticados" ON public.proveedores
FOR ALL USING (auth.role() = 'authenticated');


-- 2. TABLA INTERMEDIA PARA MAPEAR INSUMOS, PROVEEDORES Y COSTOS
CREATE TABLE IF NOT EXISTS public.proveedor_insumos (
    proveedor_id BIGINT NOT NULL REFERENCES public.proveedores(id) ON DELETE CASCADE,
    insumo_id BIGINT NOT NULL REFERENCES public.insumos(id) ON DELETE CASCADE,
    costo_especifico NUMERIC(10, 2) NOT NULL,
    es_proveedor_activo BOOLEAN NOT NULL DEFAULT false,
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (proveedor_id, insumo_id)
);
COMMENT ON TABLE public.proveedor_insumos IS 'Relaciona un insumo con un proveedor y define su costo específico y si es el proveedor principal.';

ALTER TABLE public.proveedor_insumos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir gestión de proveedor-insumo a usuarios autenticados" ON public.proveedor_insumos
FOR ALL USING (auth.role() = 'authenticated');


-- 3. FUNCIÓN Y TRIGGER PARA GARANTIZAR UN ÚNICO PROVEEDOR ACTIVO POR INSUMO
CREATE OR REPLACE FUNCTION public.asegurar_proveedor_activo_unico()
RETURNS TRIGGER AS $$
BEGIN
  -- Si el nuevo registro o la actualización establece este proveedor como activo
  IF NEW.es_proveedor_activo = TRUE THEN
    -- Pone en 'false' a todos los demás proveedores para el mismo insumo
    UPDATE public.proveedor_insumos
    SET es_proveedor_activo = FALSE
    WHERE insumo_id = NEW.insumo_id
      AND proveedor_id <> NEW.proveedor_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_proveedor_insumo_activo_change ON public.proveedor_insumos;
CREATE TRIGGER on_proveedor_insumo_activo_change
BEFORE INSERT OR UPDATE ON public.proveedor_insumos
FOR EACH ROW
EXECUTE FUNCTION public.asegurar_proveedor_activo_unico();


-- 4. ÍNDICES PARA MEJORAR EL RENDIMIENTO
CREATE INDEX IF NOT EXISTS idx_proveedores_nombre ON public.proveedores(nombre);
CREATE INDEX IF NOT EXISTS idx_proveedor_insumos_proveedor ON public.proveedor_insumos(proveedor_id);
CREATE INDEX IF NOT EXISTS idx_proveedor_insumos_insumo ON public.proveedor_insumos(insumo_id);