/*
  # Sistema de Inventario de Insumos y Control de Mermas

  1. Nuevas Tablas
    - `insumos` - Catálogo de ingredientes y materiales
      - `id` (bigint, primary key)
      - `nombre` (text, unique)
      - `descripcion` (text)
      - `unidad_medida` (text)
      - `stock_actual` (numeric)
      - `stock_minimo` (numeric)
      - `costo_unitario` (numeric)
      - `created_at` (timestamptz)

    - `producto_insumos` - Recetas que conectan productos con insumos
      - `producto_id` (bigint, FK a productos)
      - `insumo_id` (bigint, FK a insumos)
      - `cantidad_requerida` (numeric)

    - `movimientos_insumo` - Historial de movimientos de inventario
      - `id` (bigint, primary key)
      - `insumo_id` (bigint, FK a insumos)
      - `tipo_movimiento` (text)
      - `cantidad` (numeric)
      - `motivo` (text)
      - `fecha` (timestamptz)
      - `usuario_id` (uuid)

  2. Seguridad
    - Enable RLS en todas las tablas
    - Políticas para usuarios autenticados

  3. Automatización
    - Función `actualizar_stock_insumo` para mantener stock actualizado
    - Trigger que se ejecuta automáticamente en cada movimiento

  4. Índices
    - Índices optimizados para consultas frecuentes
*/

-- 1. TABLA PARA INSUMOS (INGREDIENTES Y MATERIALES)
CREATE TABLE IF NOT EXISTS public.insumos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    descripcion TEXT,
    unidad_medida TEXT NOT NULL, -- ej: 'kg', 'litro', 'unidad', 'caja'
    stock_actual NUMERIC(10, 3) NOT NULL DEFAULT 0.000,
    stock_minimo NUMERIC(10, 3) NOT NULL DEFAULT 0.000,
    costo_unitario NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.insumos IS 'Catálogo de todos los ingredientes y materiales utilizados.';

ALTER TABLE public.insumos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir gestión de insumos a usuarios autenticados" ON public.insumos
FOR ALL USING (auth.role() = 'authenticated');


-- 2. TABLA INTERMEDIA PARA RECETAS (PRODUCTOS <-> INSUMOS)
CREATE TABLE IF NOT EXISTS public.producto_insumos (
    producto_id BIGINT NOT NULL REFERENCES public.productos(id) ON DELETE CASCADE,
    insumo_id BIGINT NOT NULL REFERENCES public.insumos(id) ON DELETE CASCADE,
    cantidad_requerida NUMERIC(10, 3) NOT NULL,
    PRIMARY KEY (producto_id, insumo_id)
);
COMMENT ON TABLE public.producto_insumos IS 'Define la receta de cada producto, especificando qué insumos y en qué cantidad se usan.';

ALTER TABLE public.producto_insumos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir gestión de recetas a usuarios autenticados" ON public.producto_insumos
FOR ALL USING (auth.role() = 'authenticated');


-- 3. TABLA PARA MOVIMIENTOS DE INVENTARIO DE INSUMOS
CREATE TABLE IF NOT EXISTS public.movimientos_insumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insumo_id BIGINT NOT NULL REFERENCES public.insumos(id) ON DELETE CASCADE,
    tipo_movimiento TEXT NOT NULL, -- 'compra', 'merma', 'ajuste', 'uso_produccion'
    cantidad NUMERIC(10, 3) NOT NULL, -- Positivo para entradas, negativo para salidas
    motivo TEXT,
    fecha TIMESTAMPTZ DEFAULT now(),
    usuario_id UUID DEFAULT auth.uid()
);
COMMENT ON TABLE public.movimientos_insumo IS 'Historial de todas las entradas y salidas de stock para cada insumo.';

ALTER TABLE public.movimientos_insumo ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir gestión de movimientos de insumos a usuarios autenticados" ON public.movimientos_insumo
FOR ALL USING (auth.role() = 'authenticated');


-- 4. FUNCIÓN Y TRIGGER PARA ACTUALIZAR EL STOCK DE INSUMOS AUTOMÁTICAMENTE
CREATE OR REPLACE FUNCTION public.actualizar_stock_insumo()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.insumos
  SET stock_actual = stock_actual + NEW.cantidad
  WHERE id = NEW.insumo_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_movimiento_insumo_insert ON public.movimientos_insumo;
CREATE TRIGGER on_movimiento_insumo_insert
AFTER INSERT ON public.movimientos_insumo
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_stock_insumo();

-- 5. ÍNDICES PARA MEJORAR EL RENDIMIENTO
CREATE INDEX IF NOT EXISTS idx_insumos_nombre ON public.insumos(nombre);
CREATE INDEX IF NOT EXISTS idx_producto_insumos_producto ON public.producto_insumos(producto_id);
CREATE INDEX IF NOT EXISTS idx_producto_insumos_insumo ON public.producto_insumos(insumo_id);
CREATE INDEX IF NOT EXISTS idx_movimientos_insumo_insumo ON public.movimientos_insumo(insumo_id);

-- 6. RESTRICCIONES ADICIONALES PARA INTEGRIDAD DE DATOS
ALTER TABLE public.movimientos_insumo 
ADD CONSTRAINT movimientos_insumo_tipo_check 
CHECK (tipo_movimiento IN ('compra', 'merma', 'ajuste', 'uso_produccion'));

ALTER TABLE public.insumos 
ADD CONSTRAINT insumos_stock_actual_check 
CHECK (stock_actual >= 0);

ALTER TABLE public.insumos 
ADD CONSTRAINT insumos_stock_minimo_check 
CHECK (stock_minimo >= 0);

ALTER TABLE public.insumos 
ADD CONSTRAINT insumos_costo_unitario_check 
CHECK (costo_unitario >= 0);

ALTER TABLE public.producto_insumos 
ADD CONSTRAINT producto_insumos_cantidad_check 
CHECK (cantidad_requerida > 0);