/*
  # REFACTORIZACIÓN COMPLETA DEL MÓDULO DE PEDIDOS
  # Añade Soft Deletes, un sistema de estados y más.
*/

-- =================================================================
-- REFACTORIZACIÓN COMPLETA DEL MÓDULO DE PEDIDOS
-- Añade Soft Deletes, un sistema de estados y más.
-- =================================================================

-- 1. AÑADIR SOPORTE PARA "SOFT DELETE" (BORRADO LÓGICO)
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE public.detalles_pedido ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

-- 2. CREAR UN SISTEMA DE GESTIÓN DE ESTADOS
-- Esto nos permitirá controlar el flujo de trabajo de los pedidos.

-- Tabla para definir los estados posibles
CREATE TABLE IF NOT EXISTS public.pedido_estados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    descripcion TEXT,
    color_hex TEXT -- Para la interfaz (ej: '#FFC107' para pendiente)
);

-- Tabla para definir las transiciones válidas (el "flujo de trabajo")
CREATE TABLE IF NOT EXISTS public.estado_transiciones (
    estado_origen_id BIGINT NOT NULL REFERENCES public.pedido_estados(id),
    estado_destino_id BIGINT NOT NULL REFERENCES public.pedido_estados(id),
    PRIMARY KEY (estado_origen_id, estado_destino_id)
);

-- Modificamos la tabla 'pedidos' para usar nuestro nuevo sistema de estados
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS estado_id BIGINT REFERENCES public.pedido_estados(id);

-- Insertamos los estados iniciales
INSERT INTO public.pedido_estados (nombre, descripcion, color_hex) VALUES
    ('Pendiente', 'El pedido ha sido guardado pero no finalizado.', '#FFC107'),
    ('En Preparación', 'El pedido se está preparando en cocina.', '#2196F3'),
    ('Listo para Entrega', 'El pedido está listo para ser recogido o enviado.', '#4CAF50'),
    ('Completado', 'El pedido ha sido pagado y entregado.', '#8BC34A'),
    ('Cancelado', 'El pedido ha sido cancelado.', '#F44336')
ON CONFLICT (nombre) DO NOTHING;

-- Definimos el flujo de trabajo inicial
-- Un pedido Pendiente puede pasar a En Preparación o ser Cancelado.
INSERT INTO public.estado_transiciones (estado_origen_id, estado_destino_id) VALUES
    ((SELECT id FROM public.pedido_estados WHERE nombre = 'Pendiente'), (SELECT id FROM public.pedido_estados WHERE nombre = 'En Preparación')),
    ((SELECT id FROM public.pedido_estados WHERE nombre = 'Pendiente'), (SELECT id FROM public.pedido_estados WHERE nombre = 'Cancelado')),
    ((SELECT id FROM public.pedido_estados WHERE nombre = 'En Preparación'), (SELECT id FROM public.pedido_estados WHERE nombre = 'Listo para Entrega')),
    ((SELECT id FROM public.pedido_estados WHERE nombre = 'Listo para Entrega'), (SELECT id FROM public.pedido_estados WHERE nombre = 'Completado'))
ON CONFLICT DO NOTHING;

-- 3. ACTUALIZAR POLÍTICAS DE SEGURIDAD
-- Ahora la política de lectura principal solo muestra pedidos activos.
DROP POLICY IF EXISTS "Permitir gestión de pedidos a usuarios autenticados" ON public.pedidos;
DROP POLICY IF EXISTS "Permitir a admins gestionar pedidos activos" ON public.pedidos;
CREATE POLICY "Permitir a admins gestionar pedidos activos" ON public.pedidos
FOR ALL USING (auth.role() = 'authenticated' AND deleted_at IS NULL);

-- Política adicional para ver pedidos eliminados cuando sea necesario
CREATE POLICY "Permitir ver pedidos eliminados a admins" ON public.pedidos
FOR SELECT USING (auth.role() = 'authenticated');

-- 4. FUNCIÓN PARA OBTENER TRANSICIONES VÁLIDAS
CREATE OR REPLACE FUNCTION public.get_valid_transitions(current_estado_id BIGINT)
RETURNS TABLE(estado_id BIGINT, nombre TEXT, descripcion TEXT, color_hex TEXT) AS $$
BEGIN
  RETURN QUERY
  SELECT pe.id, pe.nombre, pe.descripcion, pe.color_hex
  FROM public.pedido_estados pe
  INNER JOIN public.estado_transiciones et ON pe.id = et.estado_destino_id
  WHERE et.estado_origen_id = current_estado_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. FUNCIÓN PARA VALIDAR TRANSICIONES DE ESTADO
CREATE OR REPLACE FUNCTION public.validate_estado_transition(
  current_estado_id BIGINT,
  new_estado_id BIGINT
) RETURNS BOOLEAN AS $$
BEGIN
  -- Permitir mantener el mismo estado
  IF current_estado_id = new_estado_id THEN
    RETURN TRUE;
  END IF;
  
  -- Verificar si la transición es válida
  RETURN EXISTS (
    SELECT 1 FROM public.estado_transiciones
    WHERE estado_origen_id = current_estado_id 
    AND estado_destino_id = new_estado_id
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. TRIGGER PARA VALIDAR TRANSICIONES DE ESTADO
CREATE OR REPLACE FUNCTION public.check_estado_transition()
RETURNS TRIGGER AS $$
DECLARE
  current_estado_id BIGINT;
BEGIN
  -- Solo validar si se está cambiando el estado_id
  IF OLD.estado_id IS DISTINCT FROM NEW.estado_id THEN
    -- Obtener el estado actual
    current_estado_id := OLD.estado_id;
    
    -- Si no hay estado actual, permitir cualquier estado inicial
    IF current_estado_id IS NULL THEN
      RETURN NEW;
    END IF;
    
    -- Validar la transición
    IF NOT public.validate_estado_transition(current_estado_id, NEW.estado_id) THEN
      RAISE EXCEPTION 'Transición de estado no válida desde % a %', 
        (SELECT nombre FROM public.pedido_estados WHERE id = current_estado_id),
        (SELECT nombre FROM public.pedido_estados WHERE id = NEW.estado_id);
    END IF;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear el trigger
DROP TRIGGER IF EXISTS trigger_check_estado_transition ON public.pedidos;
CREATE TRIGGER trigger_check_estado_transition
  BEFORE UPDATE ON public.pedidos
  FOR EACH ROW
  EXECUTE FUNCTION public.check_estado_transition();

-- 7. MIGRAR DATOS EXISTENTES AL NUEVO SISTEMA DE ESTADOS
-- Actualizar pedidos existentes para usar el nuevo sistema de estados
UPDATE public.pedidos 
SET estado_id = (
  CASE 
    WHEN estado = 'pendiente' THEN (SELECT id FROM public.pedido_estados WHERE nombre = 'Pendiente')
    WHEN estado = 'completado' THEN (SELECT id FROM public.pedido_estados WHERE nombre = 'Completado')
    WHEN estado = 'cancelado' THEN (SELECT id FROM public.pedido_estados WHERE nombre = 'Cancelado')
    ELSE (SELECT id FROM public.pedido_estados WHERE nombre = 'Pendiente')
  END
)
WHERE estado_id IS NULL;

-- 8. CREAR VISTA PARA FACILITAR CONSULTAS
CREATE OR REPLACE VIEW public.pedidos_vista AS
SELECT 
  p.*,
  pe.nombre as estado_nombre,
  pe.descripcion as estado_descripcion,
  pe.color_hex as estado_color,
  c.nombre as cliente_nombre,
  c.telefono as cliente_telefono
FROM public.pedidos p
LEFT JOIN public.pedido_estados pe ON p.estado_id = pe.id
LEFT JOIN public.clientes c ON p.cliente_id = c.id
WHERE p.deleted_at IS NULL;

-- 9. ÍNDICES ADICIONALES PARA RENDIMIENTO
CREATE INDEX IF NOT EXISTS idx_pedidos_estado_id ON public.pedidos(estado_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_deleted_at ON public.pedidos(deleted_at);
CREATE INDEX IF NOT EXISTS idx_detalles_pedido_deleted_at ON public.detalles_pedido(deleted_at);