/*
  # Añadir sistema de categorías para insumos

  1. Nueva Tabla
    - `insumo_categorias` - Tabla para almacenar las categorías de insumos
      - `id` (bigint, primary key)
      - `nombre` (text, unique)
      - `descripcion` (text)
      - `created_at` (timestamptz)
  
  2. Modificación de Tabla Existente
    - Añadir columna `categoria_id` a la tabla `insumos`
    - Crear clave foránea a `insumo_categorias`
    
  3. Seguridad
    - Habilitar RLS en la nueva tabla
    - Crear políticas de acceso para usuarios autenticados
*/

-- 1. Crear tabla de categorías de insumos
CREATE TABLE IF NOT EXISTS public.insumo_categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    descripcion TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.insumo_categorias IS 'Categorías para clasificar y organizar los insumos';

-- 2. Añadir columna de categoría a la tabla insumos
ALTER TABLE public.insumos ADD COLUMN IF NOT EXISTS categoria_id BIGINT;
ALTER TABLE public.insumos ADD CONSTRAINT insumos_categoria_id_fkey 
    FOREIGN KEY (categoria_id) REFERENCES public.insumo_categorias(id) ON DELETE SET NULL;

-- 3. Configurar seguridad
ALTER TABLE public.insumo_categorias ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir gestión de categorías de insumos a usuarios autenticados" ON public.insumo_categorias
    FOR ALL USING (auth.role() = 'authenticated');

-- 4. Crear índice para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_insumos_categoria ON public.insumos(categoria_id);