/*
  # Sistema de Cuentas por Pagar (CxP)

  1. Nuevas Tablas
    - `finanzas_cuentas_por_pagar`
      - Gestiona todas las cuentas por pagar a proveedores
      - Campos: id, proveedor_id, movimiento_financiero_id, monto_total, monto_pagado, saldo_pendiente
      - Campos adicionales: fecha_compra, fecha_vencimiento, estatus, notas, referencia_compra
      - Estatus: 'pendiente', 'pagado_parcial', 'pagado_completo', 'vencido'
    
    - `finanzas_pagos_cxp`
      - Registra cada pago individual realizado a una cuenta por pagar
      - Campos: id, cuenta_por_pagar_id, monto_pagado, metodo_pago, fecha_pago
      - Campos adicionales: movimiento_financiero_id, notas, usuario_id
      - Permite tracking completo del historial de pagos

  2. Modificaciones a Tablas Existentes
    - Agregar campos a `movimientos_insumo`:
      - proveedor_id: Para vincular compras con proveedores
      - costo_unitario: Costo por unidad en la compra
      - costo_total: Costo total de la compra (cantidad × costo_unitario)
      - referencia_compra: Número de factura/nota
      - fecha_esperada_entrega: Para tracking de entregas
      - es_credito: Boolean para indicar si la compra es a crédito o pago inmediato
      - dias_credito: Días de crédito otorgados

  3. Triggers Automáticos
    - Trigger en movimientos_insumo tipo 'compra':
      - Crea automáticamente movimiento en finanzas_movimientos
      - Si es_credito = true, crea registro en cuentas_por_pagar
      - Calcula fecha_vencimiento basada en dias_credito

  4. Funciones
    - `crear_movimiento_financiero_compra()`: Crea movimiento financiero desde compra de insumo
    - `actualizar_saldo_cxp()`: Actualiza saldos al registrar pagos
    - `marcar_cxp_vencidas()`: Función manual/cron para marcar cuentas vencidas

  5. Seguridad
    - RLS habilitado en todas las tablas
    - Solo usuarios con permiso 'finanzas.gestionar' pueden gestionar CxP
    - Auditoría completa: usuario_id en todos los cambios

  6. Índices
    - Índices optimizados para consultas frecuentes
    - Mejorar performance en reportes y dashboards
*/

-- =====================================================
-- 1. CREAR TABLA DE CUENTAS POR PAGAR
-- =====================================================
CREATE TABLE IF NOT EXISTS public.finanzas_cuentas_por_pagar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT NOT NULL REFERENCES public.proveedores(id) ON DELETE RESTRICT,
    movimiento_financiero_id BIGINT REFERENCES public.finanzas_movimientos(id) ON DELETE RESTRICT,
    movimiento_insumo_id BIGINT REFERENCES public.movimientos_insumo(id) ON DELETE RESTRICT,
    monto_total NUMERIC(10, 2) NOT NULL CHECK (monto_total > 0),
    monto_pagado NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (monto_pagado >= 0),
    saldo_pendiente NUMERIC(10, 2) NOT NULL CHECK (saldo_pendiente >= 0),
    fecha_compra TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_vencimiento DATE NOT NULL,
    estatus TEXT NOT NULL DEFAULT 'pendiente' CHECK (estatus IN ('pendiente', 'pagado_parcial', 'pagado_completo', 'vencido')),
    referencia_compra TEXT,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.finanzas_cuentas_por_pagar IS 'Gestión de cuentas por pagar a proveedores';
COMMENT ON COLUMN public.finanzas_cuentas_por_pagar.saldo_pendiente IS 'Se calcula como monto_total - monto_pagado';
COMMENT ON COLUMN public.finanzas_cuentas_por_pagar.estatus IS 'pendiente: sin pagar, pagado_parcial: pago parcial, pagado_completo: totalmente pagado, vencido: pasó fecha vencimiento';

-- =====================================================
-- 2. CREAR TABLA DE PAGOS A CUENTAS POR PAGAR
-- =====================================================
CREATE TABLE IF NOT EXISTS public.finanzas_pagos_cxp (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_por_pagar_id BIGINT NOT NULL REFERENCES public.finanzas_cuentas_por_pagar(id) ON DELETE RESTRICT,
    monto_pagado NUMERIC(10, 2) NOT NULL CHECK (monto_pagado > 0),
    metodo_pago TEXT NOT NULL,
    fecha_pago TIMESTAMPTZ NOT NULL DEFAULT now(),
    movimiento_financiero_id BIGINT REFERENCES public.finanzas_movimientos(id) ON DELETE RESTRICT,
    notas TEXT,
    usuario_id UUID DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.finanzas_pagos_cxp IS 'Registra cada pago individual realizado a cuentas por pagar';
COMMENT ON COLUMN public.finanzas_pagos_cxp.movimiento_financiero_id IS 'Vincula el pago con el movimiento financiero de egreso correspondiente';

-- =====================================================
-- 3. MODIFICAR TABLA MOVIMIENTOS_INSUMO
-- =====================================================
DO $$
BEGIN
    -- Agregar proveedor_id si no existe
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'movimientos_insumo' AND column_name = 'proveedor_id'
    ) THEN
        ALTER TABLE public.movimientos_insumo 
        ADD COLUMN proveedor_id BIGINT REFERENCES public.proveedores(id) ON DELETE SET NULL;
    END IF;

    -- Agregar costo_unitario si no existe
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'movimientos_insumo' AND column_name = 'costo_unitario'
    ) THEN
        ALTER TABLE public.movimientos_insumo 
        ADD COLUMN costo_unitario NUMERIC(10, 2) DEFAULT 0 CHECK (costo_unitario >= 0);
    END IF;

    -- Agregar costo_total si no existe
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'movimientos_insumo' AND column_name = 'costo_total'
    ) THEN
        ALTER TABLE public.movimientos_insumo 
        ADD COLUMN costo_total NUMERIC(10, 2) DEFAULT 0 CHECK (costo_total >= 0);
    END IF;

    -- Agregar referencia_compra si no existe
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'movimientos_insumo' AND column_name = 'referencia_compra'
    ) THEN
        ALTER TABLE public.movimientos_insumo 
        ADD COLUMN referencia_compra TEXT;
    END IF;

    -- Agregar fecha_esperada_entrega si no existe
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'movimientos_insumo' AND column_name = 'fecha_esperada_entrega'
    ) THEN
        ALTER TABLE public.movimientos_insumo 
        ADD COLUMN fecha_esperada_entrega DATE;
    END IF;

    -- Agregar es_credito si no existe
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'movimientos_insumo' AND column_name = 'es_credito'
    ) THEN
        ALTER TABLE public.movimientos_insumo 
        ADD COLUMN es_credito BOOLEAN DEFAULT FALSE;
    END IF;

    -- Agregar dias_credito si no existe
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'movimientos_insumo' AND column_name = 'dias_credito'
    ) THEN
        ALTER TABLE public.movimientos_insumo 
        ADD COLUMN dias_credito INTEGER DEFAULT 0 CHECK (dias_credito >= 0);
    END IF;
END $$;

COMMENT ON COLUMN public.movimientos_insumo.costo_total IS 'Costo total de la compra (cantidad × costo_unitario)';
COMMENT ON COLUMN public.movimientos_insumo.es_credito IS 'TRUE si la compra es a crédito, FALSE si es pago inmediato';
COMMENT ON COLUMN public.movimientos_insumo.dias_credito IS 'Días de crédito otorgados por el proveedor';

-- =====================================================
-- 4. FUNCIÓN: CREAR MOVIMIENTO FINANCIERO Y CXP DESDE COMPRA
-- =====================================================
CREATE OR REPLACE FUNCTION public.crear_movimiento_financiero_compra()
RETURNS TRIGGER AS $$
DECLARE
    v_categoria_compras_id BIGINT;
    v_movimiento_financiero_id BIGINT;
    v_fecha_vencimiento DATE;
    v_descripcion TEXT;
BEGIN
    -- Solo procesar si es una compra
    IF NEW.tipo_movimiento = 'compra' AND NEW.costo_total > 0 THEN
        
        -- Obtener o crear categoría "Compras de Insumos"
        SELECT id INTO v_categoria_compras_id 
        FROM public.finanzas_categorias_gastos 
        WHERE nombre = 'Compras de Insumos'
        LIMIT 1;
        
        IF v_categoria_compras_id IS NULL THEN
            INSERT INTO public.finanzas_categorias_gastos (nombre, descripcion)
            VALUES ('Compras de Insumos', 'Compras de ingredientes y materiales')
            RETURNING id INTO v_categoria_compras_id;
        END IF;

        -- Construir descripción
        v_descripcion := 'Compra de insumo';
        IF NEW.referencia_compra IS NOT NULL THEN
            v_descripcion := v_descripcion || ' - Ref: ' || NEW.referencia_compra;
        END IF;
        IF NEW.motivo IS NOT NULL THEN
            v_descripcion := v_descripcion || ' - ' || NEW.motivo;
        END IF;

        -- Crear movimiento financiero (egreso)
        INSERT INTO public.finanzas_movimientos (
            tipo,
            monto,
            descripcion,
            categoria_id,
            movimiento_insumo_id,
            proveedor_id,
            fecha_movimiento,
            estatus,
            usuario_id
        ) VALUES (
            'egreso',
            NEW.costo_total,
            v_descripcion,
            v_categoria_compras_id,
            NEW.id,
            NEW.proveedor_id,
            NEW.fecha,
            CASE WHEN NEW.es_credito THEN 'pendiente' ELSE 'pagado' END,
            NEW.usuario_id
        ) RETURNING id INTO v_movimiento_financiero_id;

        -- Si es a crédito, crear cuenta por pagar
        IF NEW.es_credito THEN
            -- Calcular fecha de vencimiento
            v_fecha_vencimiento := (NEW.fecha::DATE + (COALESCE(NEW.dias_credito, 30) || ' days')::INTERVAL)::DATE;

            INSERT INTO public.finanzas_cuentas_por_pagar (
                proveedor_id,
                movimiento_financiero_id,
                movimiento_insumo_id,
                monto_total,
                monto_pagado,
                saldo_pendiente,
                fecha_compra,
                fecha_vencimiento,
                estatus,
                referencia_compra,
                notas
            ) VALUES (
                NEW.proveedor_id,
                v_movimiento_financiero_id,
                NEW.id,
                NEW.costo_total,
                0,
                NEW.costo_total,
                NEW.fecha,
                v_fecha_vencimiento,
                'pendiente',
                NEW.referencia_compra,
                NEW.motivo
            );
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear trigger
DROP TRIGGER IF EXISTS trigger_crear_movimiento_financiero_compra ON public.movimientos_insumo;
CREATE TRIGGER trigger_crear_movimiento_financiero_compra
AFTER INSERT ON public.movimientos_insumo
FOR EACH ROW
EXECUTE FUNCTION public.crear_movimiento_financiero_compra();

-- =====================================================
-- 5. FUNCIÓN: ACTUALIZAR SALDO CXP AL REGISTRAR PAGO
-- =====================================================
CREATE OR REPLACE FUNCTION public.actualizar_saldo_cxp()
RETURNS TRIGGER AS $$
DECLARE
    v_cuenta_cxp RECORD;
    v_nuevo_estatus TEXT;
    v_movimiento_financiero_id BIGINT;
BEGIN
    -- Obtener información de la cuenta por pagar
    SELECT * INTO v_cuenta_cxp
    FROM public.finanzas_cuentas_por_pagar
    WHERE id = NEW.cuenta_por_pagar_id;

    -- Validar que el pago no exceda el saldo pendiente
    IF NEW.monto_pagado > v_cuenta_cxp.saldo_pendiente THEN
        RAISE EXCEPTION 'El monto del pago (%) excede el saldo pendiente (%)', 
            NEW.monto_pagado, v_cuenta_cxp.saldo_pendiente;
    END IF;

    -- Actualizar montos en la cuenta por pagar
    UPDATE public.finanzas_cuentas_por_pagar
    SET 
        monto_pagado = monto_pagado + NEW.monto_pagado,
        saldo_pendiente = saldo_pendiente - NEW.monto_pagado,
        updated_at = now()
    WHERE id = NEW.cuenta_por_pagar_id;

    -- Determinar nuevo estatus
    IF v_cuenta_cxp.saldo_pendiente - NEW.monto_pagado <= 0 THEN
        v_nuevo_estatus := 'pagado_completo';
    ELSIF v_cuenta_cxp.monto_pagado + NEW.monto_pagado > 0 THEN
        v_nuevo_estatus := 'pagado_parcial';
    ELSE
        v_nuevo_estatus := v_cuenta_cxp.estatus;
    END IF;

    -- Actualizar estatus
    UPDATE public.finanzas_cuentas_por_pagar
    SET estatus = v_nuevo_estatus
    WHERE id = NEW.cuenta_por_pagar_id;

    -- Crear movimiento financiero del pago (egreso)
    INSERT INTO public.finanzas_movimientos (
        tipo,
        monto,
        descripcion,
        proveedor_id,
        fecha_movimiento,
        estatus,
        metodo_pago,
        usuario_id
    ) VALUES (
        'egreso',
        NEW.monto_pagado,
        'Pago a proveedor - CxP #' || NEW.cuenta_por_pagar_id || 
        CASE WHEN NEW.notas IS NOT NULL THEN ' - ' || NEW.notas ELSE '' END,
        v_cuenta_cxp.proveedor_id,
        NEW.fecha_pago,
        'pagado',
        NEW.metodo_pago,
        NEW.usuario_id
    ) RETURNING id INTO v_movimiento_financiero_id;

    -- Actualizar el pago con el ID del movimiento financiero
    NEW.movimiento_financiero_id := v_movimiento_financiero_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear trigger
DROP TRIGGER IF EXISTS trigger_actualizar_saldo_cxp ON public.finanzas_pagos_cxp;
CREATE TRIGGER trigger_actualizar_saldo_cxp
BEFORE INSERT ON public.finanzas_pagos_cxp
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_saldo_cxp();

-- =====================================================
-- 6. FUNCIÓN: MARCAR CUENTAS VENCIDAS
-- =====================================================
CREATE OR REPLACE FUNCTION public.marcar_cxp_vencidas()
RETURNS INTEGER AS $$
DECLARE
    v_count INTEGER;
BEGIN
    UPDATE public.finanzas_cuentas_por_pagar
    SET estatus = 'vencido'
    WHERE fecha_vencimiento < CURRENT_DATE
    AND estatus IN ('pendiente', 'pagado_parcial')
    AND saldo_pendiente > 0;
    
    GET DIAGNOSTICS v_count = ROW_COUNT;
    RETURN v_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION public.marcar_cxp_vencidas IS 'Actualiza el estatus a vencido para cuentas que pasaron su fecha de vencimiento';

-- =====================================================
-- 7. ÍNDICES PARA OPTIMIZACIÓN
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_cxp_proveedor ON public.finanzas_cuentas_por_pagar(proveedor_id);
CREATE INDEX IF NOT EXISTS idx_cxp_estatus ON public.finanzas_cuentas_por_pagar(estatus);
CREATE INDEX IF NOT EXISTS idx_cxp_fecha_vencimiento ON public.finanzas_cuentas_por_pagar(fecha_vencimiento);
CREATE INDEX IF NOT EXISTS idx_cxp_fecha_compra ON public.finanzas_cuentas_por_pagar(fecha_compra);
CREATE INDEX IF NOT EXISTS idx_cxp_movimiento_insumo ON public.finanzas_cuentas_por_pagar(movimiento_insumo_id);

CREATE INDEX IF NOT EXISTS idx_pagos_cxp_cuenta ON public.finanzas_pagos_cxp(cuenta_por_pagar_id);
CREATE INDEX IF NOT EXISTS idx_pagos_cxp_fecha ON public.finanzas_pagos_cxp(fecha_pago);

CREATE INDEX IF NOT EXISTS idx_movimientos_insumo_proveedor ON public.movimientos_insumo(proveedor_id);
CREATE INDEX IF NOT EXISTS idx_movimientos_insumo_tipo ON public.movimientos_insumo(tipo_movimiento);

-- =====================================================
-- 8. SEGURIDAD - ROW LEVEL SECURITY (RLS)
-- =====================================================
ALTER TABLE public.finanzas_cuentas_por_pagar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finanzas_pagos_cxp ENABLE ROW LEVEL SECURITY;

-- Políticas para Cuentas por Pagar
DROP POLICY IF EXISTS "Permitir gestión de CxP a usuarios con permiso" ON public.finanzas_cuentas_por_pagar;
CREATE POLICY "Permitir gestión de CxP a usuarios con permiso" 
ON public.finanzas_cuentas_por_pagar 
FOR ALL 
USING (check_permission('finanzas.gestionar'));

-- Políticas para Pagos CxP
DROP POLICY IF EXISTS "Permitir gestión de pagos CxP a usuarios con permiso" ON public.finanzas_pagos_cxp;
CREATE POLICY "Permitir gestión de pagos CxP a usuarios con permiso" 
ON public.finanzas_pagos_cxp 
FOR ALL 
USING (check_permission('finanzas.gestionar'));

-- =====================================================
-- 9. AGREGAR CAMPOS ADICIONALES A PROVEEDORES
-- =====================================================
DO $$
BEGIN
    -- Agregar dias_credito_default si no existe
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'proveedores' AND column_name = 'dias_credito_default'
    ) THEN
        ALTER TABLE public.proveedores 
        ADD COLUMN dias_credito_default INTEGER DEFAULT 30 CHECK (dias_credito_default >= 0);
    END IF;

    -- Agregar limite_credito si no existe
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'proveedores' AND column_name = 'limite_credito'
    ) THEN
        ALTER TABLE public.proveedores 
        ADD COLUMN limite_credito NUMERIC(10, 2) DEFAULT 0 CHECK (limite_credito >= 0);
    END IF;
END $$;

COMMENT ON COLUMN public.proveedores.dias_credito_default IS 'Días de crédito por defecto que otorga el proveedor';
COMMENT ON COLUMN public.proveedores.limite_credito IS 'Límite de crédito autorizado con el proveedor';

-- =====================================================
-- 10. VISTAS ÚTILES
-- =====================================================

-- Vista: Resumen de CxP por Proveedor
CREATE OR REPLACE VIEW public.vista_cxp_resumen_proveedor AS
SELECT 
    p.id AS proveedor_id,
    p.nombre AS proveedor_nombre,
    COUNT(cxp.id) AS total_cuentas,
    COUNT(CASE WHEN cxp.estatus = 'pendiente' THEN 1 END) AS cuentas_pendientes,
    COUNT(CASE WHEN cxp.estatus = 'vencido' THEN 1 END) AS cuentas_vencidas,
    COALESCE(SUM(cxp.monto_total), 0) AS monto_total,
    COALESCE(SUM(cxp.monto_pagado), 0) AS monto_pagado,
    COALESCE(SUM(cxp.saldo_pendiente), 0) AS saldo_pendiente
FROM public.proveedores p
LEFT JOIN public.finanzas_cuentas_por_pagar cxp ON p.id = cxp.proveedor_id
GROUP BY p.id, p.nombre;

COMMENT ON VIEW public.vista_cxp_resumen_proveedor IS 'Resumen de cuentas por pagar agrupadas por proveedor';

-- Vista: CxP con Antigüedad
CREATE OR REPLACE VIEW public.vista_cxp_antiguedad AS
SELECT 
    cxp.*,
    p.nombre AS proveedor_nombre,
    CURRENT_DATE - cxp.fecha_vencimiento AS dias_vencidos,
    CASE 
        WHEN cxp.estatus = 'pagado_completo' THEN 'Pagado'
        WHEN CURRENT_DATE <= cxp.fecha_vencimiento THEN 'Al corriente'
        WHEN CURRENT_DATE - cxp.fecha_vencimiento BETWEEN 1 AND 30 THEN '1-30 días'
        WHEN CURRENT_DATE - cxp.fecha_vencimiento BETWEEN 31 AND 60 THEN '31-60 días'
        WHEN CURRENT_DATE - cxp.fecha_vencimiento BETWEEN 61 AND 90 THEN '61-90 días'
        ELSE 'Más de 90 días'
    END AS rango_antiguedad
FROM public.finanzas_cuentas_por_pagar cxp
INNER JOIN public.proveedores p ON cxp.proveedor_id = p.id;

COMMENT ON VIEW public.vista_cxp_antiguedad IS 'Cuentas por pagar con información de antigüedad de saldo';
