/*
  # Módulo de Finanzas v1.0

  1. Nuevas Tablas:
    - `finanzas_categorias_gastos`: Para clasificar los gastos (nómina, renta, marketing, etc.).
    - `finanzas_movimientos`: El libro mayor. Registra cada ingreso y egreso.
    - `finanzas_pagos_recurrentes`: Define gastos fijos para su proyección y automatización.

  2. Integración:
    - Los movimientos de ingresos se generarán automáticamente desde los pedidos completados.
    - Los movimientos de egresos por compra de insumos se generarán desde los movimientos de inventario.

  3. Seguridad:
    - Políticas RLS para asegurar que solo usuarios autorizados puedan gestionar las finanzas.
*/

-- Tabla para categorizar los gastos
CREATE TABLE IF NOT EXISTS public.finanzas_categorias_gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    descripcion TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.finanzas_categorias_gastos IS 'Categorías para clasificar los gastos del negocio.';

-- El "Libro Mayor": Tabla principal para todos los movimientos financieros
CREATE TABLE IF NOT EXISTS public.finanzas_movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL CHECK (tipo IN ('ingreso', 'egreso')),
    monto NUMERIC(10, 2) NOT NULL,
    descripcion TEXT NOT NULL,
    categoria_id BIGINT REFERENCES public.finanzas_categorias_gastos(id),
    pedido_id BIGINT REFERENCES public.pedidos(id), -- Para vincular ingresos a ventas
    movimiento_insumo_id BIGINT REFERENCES public.movimientos_insumo(id), -- Para vincular gastos a compras
    proveedor_id BIGINT REFERENCES public.proveedores(id),
    fecha_movimiento TIMESTAMPTZ DEFAULT now(),
    estatus TEXT NOT NULL DEFAULT 'pagado' CHECK (estatus IN ('pagado', 'pendiente', 'cancelado')),
    metodo_pago TEXT,
    usuario_id UUID DEFAULT auth.uid(),
    deleted_at TIMESTAMPTZ
);
COMMENT ON TABLE public.finanzas_movimientos IS 'Registra cada transacción de ingreso o egreso del negocio.';

-- Tabla para gestionar pagos recurrentes (renta, suscripciones, etc.)
CREATE TABLE IF NOT EXISTS public.finanzas_pagos_recurrentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion TEXT NOT NULL,
    monto NUMERIC(10, 2) NOT NULL,
    categoria_id BIGINT NOT NULL REFERENCES public.finanzas_categorias_gastos(id),
    frecuencia TEXT NOT NULL CHECK (frecuencia IN ('diario', 'semanal', 'mensual', 'anual')),
    dia_del_mes INT, -- Para pagos mensuales
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    activo BOOLEAN DEFAULT TRUE
);
COMMENT ON TABLE public.finanzas_pagos_recurrentes IS 'Define gastos recurrentes para proyecciones y recordatorios.';

-- Políticas de Seguridad
ALTER TABLE public.finanzas_categorias_gastos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir gestión de categorías de gastos a admins" ON public.finanzas_categorias_gastos FOR ALL USING (check_permission('finanzas.gestionar'));

ALTER TABLE public.finanzas_movimientos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir gestión de movimientos a admins" ON public.finanzas_movimientos FOR ALL USING (check_permission('finanzas.gestionar'));

ALTER TABLE public.finanzas_pagos_recurrentes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir gestión de pagos recurrentes a admins" ON public.finanzas_pagos_recurrentes FOR ALL USING (check_permission('finanzas.gestionar'));

-- Permiso para el nuevo módulo
INSERT INTO public.permisos (nombre, descripcion)
VALUES ('finanzas.gestionar', 'Permite acceso completo al módulo de finanzas')
ON CONFLICT (nombre) DO NOTHING;

-- Asignar permiso al rol de admin
INSERT INTO public.rol_permisos (rol_id, permiso_id)
SELECT
    (SELECT id FROM public.roles WHERE nombre = 'admin'),
    (SELECT id FROM public.permisos WHERE nombre = 'finanzas.gestionar')
ON CONFLICT (rol_id, permiso_id) DO NOTHING;