/*
  # Sistema completo de pagos y auditoría de pedidos

  1. Crear tabla de pagos
    - Tabla para registrar cada pago individual
    - Políticas de seguridad apropiadas
  
  2. Mejorar tabla de pedidos
    - Añadir campos de auditoría para finalización
    - Eliminar restricciones problemáticas
  
  3. Funciones auxiliares
    - Calcular totales pagados
    - Verificar si pedido está completamente pagado
    - Calcular saldo pendiente
  
  4. Índices para rendimiento
    - Optimizar consultas de pagos y pedidos
*/

-- =================================================================
-- SISTEMA COMPLETO DE PAGOS Y AUDITORÍA DE PEDIDOS
-- =================================================================

-- 1. CREAR TABLA PARA REGISTRAR CADA PAGO INDIVIDUAL
CREATE TABLE IF NOT EXISTS public.pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL REFERENCES public.pedidos(id),
    metodo_pago TEXT NOT NULL,
    monto NUMERIC(10, 2) NOT NULL,
    fecha_pago TIMESTAMPTZ DEFAULT now(),
    cobrado_por_usuario_id UUID REFERENCES public.usuarios(id),
    observaciones TEXT,
    insert_date TIMESTAMPTZ DEFAULT now()
);

-- Aplicar políticas de seguridad (eliminar primero si existe)
ALTER TABLE public.pagos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir gestión de pagos a usuarios autenticados" ON public.pagos;
DROP POLICY IF EXISTS "Permitir gestión de pagos a admins" ON public.pagos;
CREATE POLICY "Permitir gestión de pagos a usuarios autenticados" ON public.pagos
FOR ALL USING (auth.role() = 'authenticated');

-- 2. MEJORAR LA TABLA DE PEDIDOS CON CAMPOS DE AUDITORÍA
-- Estas columnas nos dirán quién y cuándo finalizó el pedido.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'pedidos' AND column_name = 'cobrado_por_usuario_id') THEN
    ALTER TABLE public.pedidos ADD COLUMN cobrado_por_usuario_id UUID REFERENCES public.usuarios(id);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'pedidos' AND column_name = 'fecha_finalizacion') THEN
    ALTER TABLE public.pedidos ADD COLUMN fecha_finalizacion TIMESTAMPTZ;
  END IF;
END $$;

-- 3. ELIMINAR LA RESTRICCIÓN ROTA DE 'pedidos_estado_check'
-- Esta regla antigua nos está dando problemas. La eliminaremos y la manejaremos con la tabla de transiciones.
ALTER TABLE public.pedidos DROP CONSTRAINT IF EXISTS pedidos_estado_check;

-- 4. CREAR ÍNDICES PARA MEJORAR RENDIMIENTO
CREATE INDEX IF NOT EXISTS idx_pagos_pedido_id ON public.pagos(pedido_id);
CREATE INDEX IF NOT EXISTS idx_pagos_fecha ON public.pagos(fecha_pago);
CREATE INDEX IF NOT EXISTS idx_pedidos_fecha_finalizacion ON public.pedidos(fecha_finalizacion);

-- 5. FUNCIÓN PARA CALCULAR TOTAL PAGADO DE UN PEDIDO
CREATE OR REPLACE FUNCTION public.calcular_total_pagado(pedido_id_param BIGINT)
RETURNS NUMERIC(10, 2) AS $$
DECLARE
  total_pagado NUMERIC(10, 2);
BEGIN
  SELECT COALESCE(SUM(monto), 0) INTO total_pagado
  FROM public.pagos
  WHERE pedido_id = pedido_id_param;
  
  RETURN total_pagado;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. FUNCIÓN PARA VERIFICAR SI UN PEDIDO ESTÁ COMPLETAMENTE PAGADO
CREATE OR REPLACE FUNCTION public.pedido_completamente_pagado(pedido_id_param BIGINT)
RETURNS BOOLEAN AS $$
DECLARE
  total_pedido NUMERIC(10, 2);
  total_pagado NUMERIC(10, 2);
BEGIN
  -- Obtener el total del pedido
  SELECT total INTO total_pedido
  FROM public.pedidos
  WHERE id = pedido_id_param;
  
  -- Calcular total pagado
  total_pagado := public.calcular_total_pagado(pedido_id_param);
  
  -- Verificar si está completamente pagado (con tolerancia de 0.01 para errores de redondeo)
  RETURN total_pagado >= (total_pedido - 0.01);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. FUNCIÓN PARA CALCULAR EL SALDO PENDIENTE DE UN PEDIDO
CREATE OR REPLACE FUNCTION public.calcular_saldo_pendiente(pedido_id_param BIGINT)
RETURNS NUMERIC(10, 2) AS $$
DECLARE
  total_pedido NUMERIC(10, 2);
  total_pagado NUMERIC(10, 2);
  saldo_pendiente NUMERIC(10, 2);
BEGIN
  -- Obtener el total del pedido
  SELECT total INTO total_pedido
  FROM public.pedidos
  WHERE id = pedido_id_param;
  
  -- Calcular total pagado
  total_pagado := public.calcular_total_pagado(pedido_id_param);
  
  -- Calcular saldo pendiente
  saldo_pendiente := total_pedido - total_pagado;
  
  -- Asegurar que no sea negativo
  IF saldo_pendiente < 0 THEN
    saldo_pendiente := 0;
  END IF;
  
  RETURN saldo_pendiente;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;