/*
  # Refactorización completa del módulo de pedidos

  1. Soft Delete Support
    - Añadir columnas deleted_at a pedidos y detalles_pedido
  
  2. Sistema de gestión de estados
    - Crear tabla pedido_estados para definir estados posibles
    - Crear tabla estado_transiciones para flujo de trabajo
    - Modificar tabla pedidos para usar el nuevo sistema
  
  3. Sistema de tickets/recibos
    - Crear tabla tickets para generar recibos
  
  4. Datos iniciales y políticas de seguridad
    - Insertar estados iniciales
    - Actualizar políticas RLS
*/

-- =================================================================
-- REFACTORIZACIÓN COMPLETA DEL MÓDULO DE PEDIDOS
-- =================================================================

-- 1. AÑADIR SOPORTE PARA "SOFT DELETE" (BORRADO LÓGICO)
-- Esto nos permite "archivar" pedidos en lugar de borrarlos permanentemente.
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE public.detalles_pedido ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

-- 2. CREAR UN SISTEMA DE GESTIÓN DE ESTADOS
-- Para controlar el flujo de trabajo de un pedido (ej: Pendiente -> En Preparación -> etc.)

-- Tabla para definir los estados posibles del pedido
CREATE TABLE IF NOT EXISTS public.pedido_estados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    descripcion TEXT,
    color_hex TEXT -- Para darle color a los estados en la interfaz
);

-- Tabla para definir las transiciones válidas entre estados
CREATE TABLE IF NOT EXISTS public.estado_transiciones (
    estado_origen_id BIGINT NOT NULL REFERENCES public.pedido_estados(id),
    estado_destino_id BIGINT NOT NULL REFERENCES public.pedido_estados(id),
    PRIMARY KEY (estado_origen_id, estado_destino_id)
);

-- Modificamos la tabla 'pedidos' para que use nuestro nuevo sistema de estados.
-- Mantenemos la columna 'estado' existente por compatibilidad y añadimos estado_id
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS estado_id BIGINT REFERENCES public.pedido_estados(id);

-- 3. CREAR TABLA PARA TICKETS/RECIBOS
-- Se generará un registro aquí cada vez que se finalice o guarde un pedido.
CREATE TABLE IF NOT EXISTS public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL UNIQUE REFERENCES public.pedidos(id),
    numero_ticket TEXT NOT NULL UNIQUE,
    datos_pedido_snapshot JSONB, -- Se guardará una copia "congelada" de los detalles del pedido
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. INSERTAR DATOS INICIALES PARA LOS ESTADOS
INSERT INTO public.pedido_estados (nombre, descripcion, color_hex) VALUES
    ('Pendiente', 'El pedido ha sido guardado pero no finalizado.', '#FFC107'),
    ('En Preparación', 'El pedido se está preparando en cocina.', '#2196F3'),
    ('Listo para Entrega', 'El pedido está listo para ser recogido o enviado.', '#4CAF50'),
    ('Completado', 'El pedido ha sido pagado y entregado.', '#8BC34A'),
    ('Cancelado', 'El pedido ha sido cancelado.', '#F44336')
ON CONFLICT (nombre) DO NOTHING;

-- Definir las transiciones válidas entre estados
INSERT INTO public.estado_transiciones (estado_origen_id, estado_destino_id) VALUES
    ((SELECT id FROM public.pedido_estados WHERE nombre = 'Pendiente'), (SELECT id FROM public.pedido_estados WHERE nombre = 'En Preparación')),
    ((SELECT id FROM public.pedido_estados WHERE nombre = 'Pendiente'), (SELECT id FROM public.pedido_estados WHERE nombre = 'Completado')),
    ((SELECT id FROM public.pedido_estados WHERE nombre = 'Pendiente'), (SELECT id FROM public.pedido_estados WHERE nombre = 'Cancelado')),
    ((SELECT id FROM public.pedido_estados WHERE nombre = 'En Preparación'), (SELECT id FROM public.pedido_estados WHERE nombre = 'Listo para Entrega')),
    ((SELECT id FROM public.pedido_estados WHERE nombre = 'En Preparación'), (SELECT id FROM public.pedido_estados WHERE nombre = 'Cancelado')),
    ((SELECT id FROM public.pedido_estados WHERE nombre = 'Listo para Entrega'), (SELECT id FROM public.pedido_estados WHERE nombre = 'Completado')),
    ((SELECT id FROM public.pedido_estados WHERE nombre = 'Listo para Entrega'), (SELECT id FROM public.pedido_estados WHERE nombre = 'Cancelado'))
ON CONFLICT DO NOTHING;

-- 5. CREAR FUNCIONES AUXILIARES

-- Función para obtener transiciones válidas desde un estado
CREATE OR REPLACE FUNCTION public.get_valid_transitions(current_estado_id BIGINT)
RETURNS TABLE(estado_id BIGINT, nombre TEXT, descripcion TEXT, color_hex TEXT) AS $$
BEGIN
  RETURN QUERY
  SELECT pe.id, pe.nombre, pe.descripcion, pe.color_hex
  FROM public.pedido_estados pe
  INNER JOIN public.estado_transiciones et ON pe.id = et.estado_destino_id
  WHERE et.estado_origen_id = current_estado_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Función para validar transiciones de estado
CREATE OR REPLACE FUNCTION public.check_estado_transition()
RETURNS TRIGGER AS $$
DECLARE
  current_estado_id BIGINT;
BEGIN
  -- Solo validar si se está cambiando el estado_id
  IF OLD.estado_id IS DISTINCT FROM NEW.estado_id THEN
    current_estado_id := OLD.estado_id;
    
    -- Si no hay estado actual, permitir cualquier estado inicial
    IF current_estado_id IS NULL THEN
      RETURN NEW;
    END IF;
    
    -- Validar la transición
    IF NOT EXISTS (
      SELECT 1 FROM public.estado_transiciones
      WHERE estado_origen_id = current_estado_id 
      AND estado_destino_id = NEW.estado_id
    ) THEN
      RAISE EXCEPTION 'Transición de estado no válida desde % a %', 
        (SELECT nombre FROM public.pedido_estados WHERE id = current_estado_id),
        (SELECT nombre FROM public.pedido_estados WHERE id = NEW.estado_id);
    END IF;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear trigger para validar transiciones
DROP TRIGGER IF EXISTS trigger_check_estado_transition ON public.pedidos;
CREATE TRIGGER trigger_check_estado_transition
  BEFORE UPDATE ON public.pedidos
  FOR EACH ROW
  EXECUTE FUNCTION public.check_estado_transition();

-- 6. ACTUALIZAR POLÍTICAS DE SEGURIDAD PARA CONTEMPLAR EL BORRADO LÓGICO
-- Ahora, la política de lectura principal solo debe devolver pedidos activos.
DROP POLICY IF EXISTS "Permitir gestión de pedidos a usuarios autenticados" ON public.pedidos;
DROP POLICY IF EXISTS "Permitir a admins gestionar pedidos activos" ON public.pedidos;
DROP POLICY IF EXISTS "Permitir ver pedidos eliminados a admins" ON public.pedidos;

CREATE POLICY "Permitir a admins gestionar pedidos activos" ON public.pedidos
FOR ALL USING (auth.role() = 'authenticated' AND deleted_at IS NULL);

-- Política adicional para ver pedidos eliminados cuando sea necesario
CREATE POLICY "Permitir ver pedidos eliminados a admins" ON public.pedidos
FOR SELECT USING (auth.role() = 'authenticated');

-- Habilitar RLS en las nuevas tablas
ALTER TABLE public.pedido_estados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estado_transiciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- Políticas para las nuevas tablas
CREATE POLICY "Permitir lectura de estados a usuarios autenticados" ON public.pedido_estados
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir lectura de transiciones a usuarios autenticados" ON public.estado_transiciones
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir gestión de tickets a usuarios autenticados" ON public.tickets
FOR ALL USING (auth.role() = 'authenticated');

-- 7. MIGRAR DATOS EXISTENTES
-- Actualizar pedidos existentes para usar el nuevo sistema de estados
UPDATE public.pedidos 
SET estado_id = (
  CASE 
    WHEN estado = 'pendiente' THEN (SELECT id FROM public.pedido_estados WHERE nombre = 'Pendiente')
    WHEN estado = 'completado' THEN (SELECT id FROM public.pedido_estados WHERE nombre = 'Completado')
    WHEN estado = 'cancelado' THEN (SELECT id FROM public.pedido_estados WHERE nombre = 'Cancelado')
    ELSE (SELECT id FROM public.pedido_estados WHERE nombre = 'Pendiente')
  END
)
WHERE estado_id IS NULL;

-- 8. CREAR ÍNDICES PARA MEJORAR RENDIMIENTO
CREATE INDEX IF NOT EXISTS idx_pedidos_estado_id ON public.pedidos(estado_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_deleted_at ON public.pedidos(deleted_at);
CREATE INDEX IF NOT EXISTS idx_detalles_pedido_deleted_at ON public.detalles_pedido(deleted_at);
CREATE INDEX IF NOT EXISTS idx_tickets_pedido_id ON public.tickets(pedido_id);
CREATE INDEX IF NOT EXISTS idx_tickets_numero ON public.tickets(numero_ticket);